# Generated by Django 4.2 on 2024-07-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='resume',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
    ]
