# Generated by Django 4.2 on 2024-06-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('short_description', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('main_foto', models.ImageField(default='img/unsplash-photo-1.jpg', upload_to='img/', verbose_name='Фото рецепта')),
                ('body_text', models.TextField(max_length=10000)),
                ('code_url', models.URLField()),
                ('production_url', models.URLField()),
                ('pub_date', models.DateField()),
                ('technologies_id', models.ManyToManyField(to='portfolio.technologies')),
            ],
        ),
    ]
