# Generated by Django 4.2 on 2024-07-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_technologies_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='main_foto',
            field=models.ImageField(default='img/unsplash-photo-1.jpg', upload_to='img/', verbose_name='Project main photo'),
        ),
        migrations.AlterField(
            model_name='technologies',
            name='badge',
            field=models.ImageField(default='img/badges/icons8-python-48.png', upload_to='img/badges', verbose_name='Badge'),
        ),
    ]
