# Generated by Django 4.2 on 2024-07-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_main_foto_alter_technologies_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologies',
            name='badge',
            field=models.ImageField(default='', upload_to='badges', verbose_name='Badge'),
        ),
    ]
