# Generated by Django 4.2 on 2024-07-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_project_main_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technologies_id',
            field=models.ManyToManyField(related_name='tags', to='portfolio.technologies'),
        ),
    ]
