# Generated by Django 4.2 on 2024-07-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_technology_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='slug',
            field=models.SlugField(default=None, help_text='Идентификатор страницы для URL; разрешены символы латиницы, цифры, дефис и подчёркивание.', max_length=64, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
