# Generated by Django 4.2 on 2024-07-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_technology_slug_alter_technology_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technologies_id',
            field=models.ManyToManyField(related_name='projects', to='portfolio.technology'),
        ),
    ]
