# Generated by Django 4.2 on 2024-08-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_project_body_text_en_project_body_text_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description_ru',
        ),
        migrations.AddField(
            model_name='project',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
